[tool.poetry]
name = "nominal"
version = "0.0.1"
description = "Automate Nominal workflows in Python"
authors = ["JP <jack@nominal.io>", "Michael Bauer <michael@nominal.io>"]
readme = "README.md"
packages = [
    {include = "nominal/**/*.py"},
]
include = ["README.md", "LICENSE"]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.dev-dependencies]
ruff = "^ 0.4.2"

[tool.distutils.bdist_wheel]
universal = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
